apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wt24xml6q-python
  janus-idp.io/tekton: wt24xml6q-python
  backstage.io/kubernetes-id: wt24xml6q-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wt24xml6q-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
